version: "3"
services:
        login-app:
            container_name: login-app
            build: ./ 
            # image: latest123/login-app
            restart: always
            ports:
              - "7500:7500"
            links:
              - mongo
        mongo:
              container_name: mongo
              image: mongo
              expose:
                - 27017
